spes: hals: Add missing assert.h
On initial  Android-15-ap3a, The build was failing with the following error:

FAILED: target  C++: vendor.qti.hardware.display.composer-service <= device/xiaomi/spes/hals/display/composer/hwc_buffer_sync_handler.cpp
error: use of undeclared identifier 'assert'

This issue was due to the missing #include <assert.h> in hals/display/composer/hwc_buffer_sync_handler.cpp. Adding this include resolves the error, allowing the build to complete successfully.

Signed-off-by: tanvirr007 <md.tanvirhasannijum@gmail.com>