spes: hals: Fix std::all_of return value warnings
Modified color_manager.cpp to address compiler warnings about ignored return values from std::all_of. Added casts to void to explicitly indicate that the return values are intentionally ignored. This change resolves issues with the [[nodiscard]] attribute.

Full Error:
FAILED: target  C++: libsdmcore <= device/xiaomi/spes/hals/display/sdm/libs/core/color_manager.cpp
Outputs: out/target/product/spes/obj/SHARED_LIBRARIES/libsdmcore_intermediates/color_manager.o
Error: exited with code: 1
Command: /bin/bash -c "PWD=/proc/self/cwd /usr/bin/ccache prebuilts/clang/host/linux-x86/clang-r522817/bin/clang++ -I device/xiaomi/spes/hals/display/sdm/libs/core -I out/target/product/spes/obj/SHARED_LIBRARIES/libsdmcore_intermediates -I out/target/product/spes/gen/SHARED_LIBRARIES/libsdmcore_intermediates    -Iexternal/libdrm/include/drm -Iexternal/libdrm/android -Iexternal/libdrm/include/drm -Iexternal/libdrm/android -isystem external/libdrm -isystem external/libdrm   -Iprebuilts/clang/host/linux-x86/clang-r522817/android_libc++/platform/aarch64/include/c++/v1 -Iprebuilts/clang/host/linux-x86/clang-r522817/include/c++/v1 -isystem out/soong/.intermediates/bionic/libc/libc/android_vendor_arm64_armv8-a_shared/gen/include -isystem bionic/libc/kernel/uapi/asm-arm64 -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/android/scsi -isystem bionic/libc/kernel/android/uapi     -Idevice/xiaomi/spes/hals/display/include -Idevice/xiaomi/spes/hals/display/libcopybit -Idevice/xiaomi/spes/hals/display/libdrmutils -Idevice/xiaomi/spes/hals/display/libqdutils -Idevice/xiaomi/spes/hals/display/libqservice -Idevice/xiaomi/spes/hals/display/gpu_tonemapper -Idevice/xiaomi/spes/hals/display/sdm/include -Idevice/xiaomi/spes/hals/display/gralloc -Idevice/xiaomi/spes/hals/display/libhistogram -Ihardware/libhardware/include_all -Ihardware/libhardware/include_vendor -Isystem/media/audio/include -Isystem/core/libcutils/include_outside_system -Isystem/core/libsystem/include -Ivendor/qcom/opensource/commonsys-intf/display/gralloc -Ivendor/qcom/opensource/commonsys-intf/display/include -Ivendor/qcom/opensource/commonsys-intf/display/libqdmetadata -Ivendor/qcom/opensource/commonsys-intf/display/services -Idevice/xiaomi/spes/hals/display/libdebug -Iout/soong/.intermediates/vendor/blaze/build/soong/generated_kernel_includes/gen/usr/audio/include/uapi -Iout/soong/.intermediates/vendor/blaze/build/soong/generated_kernel_includes/gen/usr/include -Iout/soong/.intermediates/vendor/blaze/build/soong/generated_kernel_includes/gen/usr/include/audio -Iout/soong/.intermediates/vendor/blaze/build/soong/generated_kernel_includes/gen/usr/include/audio/include/uapi -Iout/soong/.intermediates/vendor/blaze/build/soong/generated_kernel_includes/gen/usr/techpack/audio/include   -isystem out/target/product/spes/obj/include -c  -Werror=implicit-function-declaration -D__BIONIC_DEPRECATED_PAGE_SIZE_MACRO -O2 -Wall -Wextra -Winit-self -Wpointer-arith -Wunguarded-availability -Werror=date-time -Werror=int-conversion -Werror=pragma-pack -Werror=pragma-pack-suspicious-include -Werror=sizeof-array-div -Werror=string-plus-int -Werror=unreachable-code-loop-increment -Wno-error=deprecated-declarations -Wno-c99-designator -Wno-gnu-folding-constant -Wno-inconsistent-missing-override -Wno-error=reorder-init-list -Wno-reorder-init-list -Wno-sign-compare -Wno-unused -DANDROID -DNDEBUG -UDEBUG -D__compiler_offsetof=__builtin_offsetof -D__ANDROID_UNAVAILABLE_SYMBOLS_ARE_WEAK__ -faddrsig -fdebug-default-version=5 -fcolor-diagnostics -ffp-contract=off -fno-exceptions -fno-strict-aliasing -fmessage-length=0 -fno-relaxed-template-template-args -gsimple-template-names -gz=zstd -no-canonical-prefixes -Wno-error=format -fdebug-prefix-map=/proc/self/cwd= -ftrivial-auto-var-init=zero -Wno-unused-command-line-argument -g -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=format-security -nostdlibinc -fdebug-info-for-profiling -march=armv8-a   -Wimplicit-fallthrough -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-gnu-include-next -fvisibility-inlines-hidden  -std=gnu++20   -fno-rtti -fno-operator-names -Wno-unused-parameter -DLOG_TAG=\\\"SDM\\\" -Wno-missing-field-initializers -Wall -Werror -DUSE_GRALLOC1 -DUSE_COLOR_METADATA -D__ARM_HAVE_NEON -DMASTER_SIDE_CP -DVIDEO_MODE_DEFER_RETIRE_FENCE -DUSER_DEBUG -isystem external/libdrm -DPP_DRM_ENABLE -D__ANDROID_VNDK__ -D__ANDROID_VENDOR__ -D__ANDROID_VENDOR_API__=202404 -fPIC -fsanitize-ignorelist=build/soong/cc/config/integer_overflow_blocklist.txt -fsanitize=signed-integer-overflow,unsigned-integer-overflow -fsanitize-trap=all -fsanitize-minimal-runtime -fno-sanitize-trap=integer -fno-sanitize-recover=integer -fno-sanitize=implicit-integer-sign-change -fno-sanitize=unsigned-shift-base -DANDROID_STRICT -target aarch64-linux-android10000   -Werror=bool-operation -Werror=format-insufficient-args -Werror=implicit-int-float-conversion -Werror=int-in-bool-context -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=xor-used-as-pow -Wno-void-pointer-to-enum-cast -Wno-void-pointer-to-int-cast -Wno-pointer-to-int-cast -Werror=fortify-source -Wno-unused-variable -Wno-missing-field-initializers -Wno-packed-non-pod -Werror=address-of-temporary -Werror=incompatible-function-pointer-types -Werror=null-dereference -Werror=return-type -Wno-tautological-constant-compare -Wno-tautological-type-limit-compare -Wno-implicit-int-float-conversion -Wno-tautological-overlap-compare -Wno-deprecated-copy -Wno-range-loop-construct -Wno-zero-as-null-pointer-constant -Wno-deprecated-anon-enum-enum-conversion -Wno-deprecated-enum-enum-conversion -Wno-pessimizing-move -Wno-non-c-typedef-for-linkage -Wno-align-mismatch -Wno-error=unused-but-set-variable -Wno-error=unused-but-set-parameter -Wno-error=deprecated-builtins -Wno-error=deprecated -Wno-error=single-bit-bitfield-constant-conversion -Wno-error=enum-constexpr-conversion -Wno-error=invalid-offsetof -Wno-error=thread-safety-reference-return -Wno-deprecated-dynamic-exception-spec -Wno-vla-cxx-extension   -MD -MF out/target/product/spes/obj/SHARED_LIBRARIES/libsdmcore_intermediates/color_manager.d -o out/target/product/spes/obj/SHARED_LIBRARIES/libsdmcore_intermediates/color_manager.o device/xiaomi/spes/hals/display/sdm/libs/core/color_manager.cpp"
Output:
[1mdevice/xiaomi/spes/hals/display/sdm/libs/core/color_manager.cpp:727:5: [0m[0;1;31merror: [0m[1mignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result][0m
  727 |     std::all_of(states_.begin(), states_.end(),[0m
      | [0;1;32m    ^~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[0m  728 |       [](const FeatureInterface *p) {[0m
      | [0;1;32m      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[0m  729 |       if (p) {delete p;} return true;});[0m
      | [0;1;32m      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[0m[1mdevice/xiaomi/spes/hals/display/sdm/libs/core/color_manager.cpp:748:3: [0m[0;1;31merror: [0m[1mignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result][0m
  748 |   std::all_of(states_.begin(), states_.end(),[0m
      | [0;1;32m  ^~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[0m  749 |     [](const FeatureInterface *p)[0m
      | [0;1;32m    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[0m  750 |     {if (p) {delete p;} return true;});[0m
      | [0;1;32m    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[0m2 errors generated.

Signed-off-by: tanvirr007 <md.tanvirhasannijum@gmail.com>